# Generated by Django 3.0.7 on 2021-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_customuser_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
    ]
