# Generated by Django 3.0.7 on 2021-09-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('from_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='database_test',
            new_name='database_add_test',
        ),
    ]
